# Generated by Django 3.2.5 on 2021-07-24 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todoapp', '0004_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='completed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='task_title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterOrderWithRespectTo(
            name='tasks',
            order_with_respect_to='completed',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='task',
        ),
    ]
